import unicodedata

CODIGO_IATA_POR_PAIS = {
    "AFGANISTAN": "AF",
    "ALEMANIA": "DE",
    "ALBANIA": "AL",
    "ALGERIA": "DZ",
    "ANGOLA": "AO",
    "ANTIGUA Y BARBUDA": "AG",
    "ARABIA SAUDITA": "SA",
    "ARGENTINA": "AR",
    "ARMENIA": "AM",
    "ARUBA": "AW",
    "AUSTRALIA": "AU",
    "AUSTRIA": "AT",
    "AZERBAIYAN": "AZ",
    "BAHAMAS": "BS",
    "BAHREIN": "BH",
    "BANGLADESH": "BD",
    "BARBADOS": "BB",
    "BELARUS": "BY",
    "BELGICA": "BE",
    "BELICE": "BZ",
    "BENIN": "BJ",
    "BOLIVIA": "BO",
    "BOSNIA Y HERZEGOVINA": "BA",
    "BOTSWANA": "BW",
    "BRASIL": "BR",
    "BRUNEI": "BN",
    "BULGARIA": "BG",
    "BURKINA FASO": "BF",
    "BURUNDI": "BI",
    "CABO VERDE": "CV",
    "CAMBOYA": "KH",
    "CAMERUN": "CM",
    "CANADA": "CA",
    "CATAR": "QA",
    "CHAD": "TD",
    "CHILE": "CL",
    "CHINA": "CN",
    "CHIPRE": "CY",
    "COLOMBIA": "CO",
    "COMORAS": "KM",
    "CONGO": "CG",
    "CONGO REPUBLICA DEMOCRATICA": "CD",
    "COREA DEL NORTE": "KP",
    "COREA DEL SUR": "KR",
    "COSTA DE MARFIL": "CI",
    "COSTA RICA": "CR",
    "CROACIA": "HR",
    "CUBA": "CU",
    "DINAMARCA": "DK",
    "DJIBOUTI": "DJ",
    "DOMINICA": "DM",
    "ECUADOR": "EC",
    "EGIPTO": "EG",
    "EL SALVADOR": "SV",
    "EMIRATOS ARABES UNIDOS": "AE",
    "ESLOVENIA": "SI",
    "ESPANA": "ES",
    "ESTADOS UNIDOS": "US",
    "ESTONIA": "EE",
    "ETIOPIA": "ET",
    "FILIPINAS": "PH",
    "FINLANDIA": "FI",
    "FRANCIA": "FR",
    "GABON": "GA",
    "GAMBIA": "GM",
    "GEORGIA": "GE",
    "GHANA": "GH",
    "GRECIA": "GR",
    "GUATEMALA": "GT",
    "GUINEA": "GN",
    "GUINEA ECUATORIAL": "GQ",
    "GUYANA": "GY",
    "HAITI": "HT",
    "HONDURAS": "HN",
    "HONG KONG": "HK",
    "HUNGRIA": "HU",
    "INDIA": "IN",
    "INDONESIA": "ID",
    "IRAK": "IQ",
    "IRAN": "IR",
    "IRLANDA": "IE",
    "ISLANDIA": "IS",
    "ISLAS BAHAMAS": "BH",
    "ISRAEL": "IL",
    "ITALIA": "IT",
    "JAMAICA": "JM",
    "JAPON": "JP",
    "JORDANIA": "JO",
    "KAZAJSTAN": "KZ",
    "KENIA": "KE",
    "KIRGUISTAN": "KG",
    "KOSOVO": "XK",
    "KUBAIT": "KW",
    "LAOS": "LA",
    "LESOTO": "LS",
    "LETONIA": "LV",
    "LIBANO": "LB",
    "LIBERIA": "LR",
    "LIBIA": "LY",
    "LITUANIA": "LT",
    "LUXEMBURGO": "LU",
    "MACAO": "MO",
    "MACEDONIA DEL NORTE": "MK",
    "MADAGASCAR": "MG",
    "MALASIA": "MY",
    "MALAWI": "MW",
    "MALDIVAS": "MV",
    "MALI": "ML",
    "MALTA": "MT",
    "MARRUECOS": "MA",
    "MAURICIO": "MU",
    "MAURITANIA": "MR",
    "MEXICO": "MX",
    "MICRONESIA": "FM",
    "MOLDAVIA": "MD",
    "MONGOLIA": "MN",
    "MONTENEGRO": "ME",
    "MOZAMBIQUE": "MZ",
    "NAMIBIA": "NA",
    "NEPAL": "NP",
    "NICARAGUA": "NI",
    "NIGER": "NE",
    "NIGERIA": "NG",
    "NORUEGA": "NO",
    "NUEVA ZELANDA": "NZ",
    "PAISES BAJOS": "NL",
    "PAKISTAN": "PK",
    "PALAU": "PW",
    "PANAMA": "PA",
    "PAPUA NUEVA GUINEA": "PG",
    "PARAGUAY": "PY",
    "PERU": "PE",
    "POLONIA": "PL",
    "PORTUGAL": "PT",
    "REINO UNIDO": "GB",
    "REPUBLICA CENTROAFRICANA": "CF",
    "REPUBLICA CHECA": "CZ",
    "REPUBLICA DEMOCRATICA DEL CONGO": "CD",
    "REPUBLICA DOMINICANA": "DO",
    "REPUBLICA ESLOVACA": "SK",
    "RUSIA": "RU",
    "SALOMON": "SB",
    "SAN MARINO": "SM",
    "SAN VICENTE Y LAS GRANADINAS": "VC",
    "SANTO TOME Y PRINCIPE": "ST",
    "SENEGAL": "SN",
    "SERBIA": "RS",
    "SEYCHELLES": "SC",
    "SIERRA LEONA": "SL",
    "SINGAPUR": "SG",
    "SIRIA": "SY",
    "SOMALIA": "SO",
    "SUDAN": "SD",
    "SUECIA": "SE",
    "SUIZA": "CH",
    "TAILANDIA": "TH",
    "TANZANIA": "TZ",
    "TOGO": "TG",
    "TONGA": "TO",
    "TRINIDAD Y TOBAGO": "TT",
    "TUNEZ": "TN",
    "TURQUIA": "TR",
    "UCRANIA": "UA",
    "UGANDA": "UG",
    "URUGUAY": "UY",
    "UZBEKISTAN": "UZ",
    "VENEZUELA": "VE",
    "VIETNAM": "VN",
    "YEMEN": "YE",
    "ZAMBIA": "ZM",
    "ZIMBABUE": "ZW",
}

SINONIMOS_PAIS = {
    "US": "ESTADOS UNIDOS",
    "USA": "ESTADOS UNIDOS",
    "EEUU": "ESTADOS UNIDOS",
    "UK": "REINO UNIDO",
    "GB": "REINO UNIDO",
    "INGLATERRA": "REINO UNIDO",
    "HOLANDA": "PAISES BAJOS",
    "CATALUNA": "ESPANA",
    "ANDORRA": "ESPANA",
    "REP DOMINICANA": "REPUBLICA DOMINICANA",
    "REP. DOMINICANA": "REPUBLICA DOMINICANA",
    "DOMINICANA": "REPUBLICA DOMINICANA",
}


def normalizar_texto(valor):
    if valor is None:
        return ""
    texto = str(valor).replace("\ufeff", "").strip()
    if not texto:
        return ""
    descompuesto = unicodedata.normalize("NFKD", texto)
    plano = "".join(c for c in descompuesto if not unicodedata.combining(c))
    plano = plano.replace("\t", " ").replace("\n", " ")
    return " ".join(plano.upper().split())


def codigo_iata(destino):
    clave = normalizar_texto(destino)
    if not clave:
        return None
    if clave in SINONIMOS_PAIS:
        clave = SINONIMOS_PAIS[clave]
    if len(clave) == 2 and clave in set(CODIGO_IATA_POR_PAIS.values()):
        return clave
    return CODIGO_IATA_POR_PAIS.get(clave)


def nombre_pais_por_iata(codigo):
    clave = normalizar_texto(codigo)
    for pais, iata in CODIGO_IATA_POR_PAIS.items():
        if iata == clave:
            return pais
    return clave


def paises_soportados():
    return sorted(CODIGO_IATA_POR_PAIS)
